#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  # amixer -q sset Master 5%+
  volume.sh down
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  # amixer -q sset Master toggle
  volume.sh mute
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  # amixer -q sset Master 5%-
  volume.sh up
fi

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  CURRENT=$(pactl get-default-sink | cut -d . -f2)
  if [[ "${CURRENT}" == "usb-GeneralPlus_USB_Audio_Device-00" ]]; then
    echo " ${volume}%"
    echo " ${volume}%"
    echo ""
  else
    echo " ${volume}%"
    echo " ${volume}%"
    echo ""
  fi

else
  echo " off"
  echo " off"
  echo ""
fi
