#!/bin/bash
# Based on https://aur.archlinux.org/packages/playerctl/

INSTANCE="${BLOCK_INSTANCE}"

if [[ "${INSTANCE}" != "" ]]; then
  ARGUMENTS="--player ${INSTANCE}"
  ps -e | grep "${INSTANCE}" &> /dev/null
fi
if [ $? == 1 ]; then
    exit 0
fi

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    $(playerctl ${ARGUMENTS} previous)
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    $(playerctl ${ARGUMENTS} play-pause)
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    $(playerctl ${ARGUMENTS} next)
fi

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)
INFO_TITLE=$(playerctl ${ARGUMENTS} metadata title)
INFO_ALBUM=$(playerctl ${ARGUMENTS} metadata album)
INFO_ARTIST=$(playerctl ${ARGUMENTS} metadata artist)

TEXT=" ${INFO_ARTIST} - ${INFO_TITLE}"
MAX_LENGTH=52

if [[ "${INFO_TITLE}" != "" ]] && [[ "${INFO_ARTIST}" != "" ]] && [[ "${PLAYER_STATUS}" = "Playing" ]]; then
  if [[ "${#TEXT}" -gt "$MAX_LENGTH" ]]; then
    TEXT="${TEXT:0:${MAX_LENGTH}}..."
  fi

  echo "$TEXT"
  echo "$TEXT"
  echo ""
fi

